### ISSUE TITLE
How to run single method?

### ISSUE THREAD

**Issue by Hubbitus** [browncoat-ninjas/nimoy#14]
Could you please add such possibility?
In help (version 0.0.1b7) I see I can only provide file name as minimal piece:
```
$ nimoy --help
usage: nimoy [-h] [S [S ...]]

Run a suite of Nimoy specs.

positional arguments:
  S           A path to a spec file to execute or a directory to scan for spec
              files

optional arguments:
  -h, --help  show this help message and exit
```

**Comment by noamt** [comment]
Fixed with PR #18 .
You can now run specific features with the command line using `some_spec.py::SpecName` , `some_spec.py::SpecName::feature_name` or `some_spec.py::feature_name`
