### ISSUE TITLE
Add smart failure reporting

### ISSUE THREAD

**Issue by noamt** [browncoat-ninjas/nimoy#20]
Like http://spockframework.org/spock/docs/1.3/spock_primer.html#_conditions

**Comment by artamonovkirill** [comment]
I believe here spock relies on [power assert](http://docs.groovy-lang.org/next/html/documentation/core-testing-guide.html#_power_assertions) feature of Groovy.

**Comment by noamt** [comment]
Yes. Needs a Python impl

**Comment by artamonovkirill** [comment]
@noamt, do you have any ideas which libraries or Python features might be useful there? I'd like to dig further, but my Python ecosystem and features knowledge is rather limited (I mostly did Java development).

**Comment by noamt** [comment]
The closest thing to my knowledge is the py hamcrest matcher

**Comment by noamt** [comment]
Alpha version of this feature has been merged in https://github.com/browncoat-ninjas/nimoy/commit/b21c781ead8ab052ea19f2a37e5aa2144264666a
