### ISSUE TITLE
Implement mocking with shift left and shift right operator

### ISSUE THREAD

**Issue by tanayseven** [browncoat-ninjas/nimoy#9]
I would like to contribute to the existing mocking which is there is Spock which is similar to the following:

```python
    def my_feature_method(self):
        with setup:
            the_mock = mock.Mock()

        with when:
            the_mock.do_something() >> 5

        with then:
            the_mock.do_something() == 5
```

This would mean adding functionality to python operators which are `>>`, `<<`

What do you think about it?

**Comment by noamt** [comment]
Please correct me if I'm wrong, `<<` means "return the value to the right of the expression, once the left value of the expression is called" ?
If so, what does `>>` mean?

**Comment by tanayseven** [comment]
The `>>` operator says that the call to the mock should return that one value every time.
The `<<` operator says that the call to the mock should return the next value in the array everytime it is called.

```
    def my_feature_method(self):
        with setup:
            the_mock = mock.Mock()

        with when:
            the_mock.do_something() << [5, 6, 7]

        with then:
            the_mock.do_something() == 5
            the_mock.do_something() == 6
            the_mock.do_something() == 7
```
That's how I know things work in Spock.

**Comment by noamt** [comment]
Sounds like a great idea!
Syntactically it should be possible as well

**Comment by tanayseven** [comment]
Yeah, it appears to be syntactically possible. So should I implement it and raise a PR?

**Comment by noamt** [comment]
Sure, I'd be glad!
Ping my on twitter @NoamTenne if you need any help

**Comment by tanayseven** [comment]
Sure!

**Comment by noamt** [comment]
Resolved
